---
# all, none, or list of linter keys
ACTION_ZIZMOR_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
APPLY_FIXES: all
CLEAR_REPORT_FOLDER: true
IGNORE_GITIGNORED_FILES: true
JSON_PRETTIER_CLI_LINT_MODE: project
JSON_PRETTIER_PRE_COMMANDS:
  - command: npm i --workspaces=false
    continue_if_failed: true
    cwd: workspace
    secured_env: true
    tag: default
SHOW_ELAPSED_TIME: true
YAML_PRETTIER_CLI_LINT_MODE: project
YAML_PRETTIER_PRE_COMMANDS:
  - command: npm i --workspaces=false
    continue_if_failed: true
    cwd: workspace
    secured_env: true
    tag: default
